### ISSUE TITLE
Package sync

### ISSUE THREAD

**Issue by Slydew** [engswee/flashpipe#13]
Dear,

We use package overview, Document and Tag.

Does it possible to Sync/Dump there package info too ?

Best Regards

**Comment by engswee** [comment]
Can you be more specific? It would be useful to provide some examples

**Comment by Slydew** [comment]
Sure 👍 

On Sandbox, Devs write Overview, Documents and Tag

![image](https://user-images.githubusercontent.com/2440216/198242650-baead070-061f-4a95-9f27-b60e963f952e.png)

We need to have there informations Sync and uploaded on Dev environment too.

Does it already possible ?

Thanks

**Comment by engswee** [comment]
Currently there is no functionality in FlashPipe to sync package level information. From the API provided by SAP, looks like syncing of the overview/description could be possible, but documents and tags will need further investigation.

**Comment by engswee** [comment]
Hi @Slydew, latest release 2.7.0 [https://github.com/engswee/flashpipe/releases/tag/2.7.0](url) now supports sync and update of integration package. Documents are not supported by the standard API so those are not synced.
