### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Slydew** [engswee/flashpipe#14]
Dear,

Sorry, i don't find details documentation for all parameters :
      - name: 'Deploy Groovy XML Transformation to runtime'
        run: /usr/bin/deploy_runtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: <iflow_id>
          DELAY_LENGTH: <delay_in_seconds> # Optional
          MAX_CHECK_LIMIT: <max_check_limit> # Optional          
          COMPARE_VERSIONS: <compare_versions> # Optional
          
 Thank a lot for your great job !

**Comment by engswee** [comment]
You can find it here, under point 2.
https://engswee.github.io/flashpipe/unix-scripts.html
