### ISSUE TITLE
Sync : Message mapping artefac not sync

### ISSUE THREAD

**Issue by Slydew** [engswee/flashpipe#17]
Dear,

Form a package, Integration flow artefact sync but message mapping artefact doen't sync.

Regards

**Comment by Slydew** [comment]
Seem the same for Script Collection

**Comment by engswee** [comment]
Support for these artefact types was only added recently to the public OData APIs. I'll add these to the back log.

**Comment by Slydew** [comment]
Dear,

Where we could find there public OData APIs ? 
I could try to implement it !

Thanks

**Comment by engswee** [comment]
You can find them here https://api.sap.com/api/IntegrationContent/resource/Message_Mappings

**Comment by engswee** [comment]
@Slydew - support for message mapping, script collection and value mapping has now been added in [release 3.0.0](https://github.com/engswee/flashpipe/releases/tag/v3.0.0)

You can find out more in this [public announcement of the release](https://equaliseit.com/go-go-flashpipe-major-version-v3-0-0-release/)
