### ISSUE TITLE
update_designtime_artifact

### ISSUE THREAD

**Issue by Slydew** [engswee/flashpipe#18]
Dear,

Is it possible to not set as mandatory there parameters ?
IFLOW_NAME and use Manifest Bundle-Name by default
PACKAGE_NAME and use package.json Name by default

Best regards

**Comment by engswee** [comment]
Currently no. I will need to look into the impact of implementing such a change.

**Comment by engswee** [comment]
@Slydew - in [release v3.2.0](https://github.com/engswee/flashpipe/releases/tag/v3.2.0) IFlow/Artifact name now takes the value from MANIFEST.MF if it is not provided via the parameter. I won't be introducing a similar change for the package, so will be closing this issue.
