### ISSUE TITLE
Sync designtime artifact is not updating to GitHub Repository

### ISSUE THREAD

**Issue by xprbj2212** [engswee/flashpipe#21]
Hi Engswee,

Few weeks back I used Sync design time artifact workflow and it successfully syncs the content to GitHub Repository.

Today while executing same workflow it is not syncing contents to GitHub Repository even though logs shows successful execution.
Attached logs for reference
[logs_2.zip](https://github.com/engswee/flashpipe/files/12846540/logs_2.zip)
Please check and let me know if any further details required.

**Comment by engswee** [comment]
Thanks @xprbj2212 for reporting this issue. It was because of a missing condition in https://github.com/engswee/flashpipe-action. It should be fixed now. Can you please give it a try?

**Comment by xprbj2212** [comment]
Thanks @engswee . It is working now.

**Comment by engswee** [comment]
Great. Thanks for confirming.
