### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by Slydew** [engswee/flashpipe#23]
Dear,

Did we have roadmap about unit test with Flashpipe 3 ?
If not what we could use to do there in it ?

Certainly I could use Flashpipe3 CLI and Flashpipe 2 for testing on CF.

Regards

**Comment by engswee** [comment]
Could you provide more details into what you are trying to achieve? What are you trying to test?

Can you check if the example in the github-actions branch below is similar to your use case?
https://github.com/engswee/flashpipe-demo/tree/github-actions

**Comment by Slydew** [comment]
Sorry, 

I used class [io.github.engswee.flashpipe.cpi.simulation.Simulator](https://github.com/engswee/flashpipe/blob/main/src/main/groovy/io/github/engswee/flashpipe/cpi/simulation/Simulator.groovy) for mapping UT.

Sure I could use it like your sample  for groovy UT.

regards

**Comment by Slydew** [comment]
Will we have simulator API  on CF  ? 
Any road map for that ? and for Flashpipe ?

**Comment by engswee** [comment]
The non-public simulation API that works on Neo does not work on CF. SAP has on the roadmap for a public API for simulation, but when that will be delivered is up to SAP which it out of my control. Only after it is publicly available from SAP, I can then assess the feasibility of incorporating it into FlashPipe.

In short: if you are on CF, there are no current plans for simulation capability on FlashPipe.

**Comment by Slydew** [comment]
Thanks you
