### ISSUE TITLE
Integration Package Description and Iflow Description - Not Getting Updated

### ISSUE THREAD

**Issue by xprbj2212** [engswee/flashpipe#30]
@engswee - We observed when we deploy Integration package and Iflow from GitHub repository to Tenant (Test, Prd) descriptions are not getting updated in Test and Prd Tenants even though descriptions are maintained in Dev Tenant

We tried using flashpipe versions - 3.1.0 and 3.2.3.

Is this limitation of the standard API or we need to maintain any metadata file after performing synch from Dev Tenant to GitHub repository. Please clarify and let me know if any further details required.

**Comment by xprbj2212** [comment]
@engswee I tried executing with "Sync Package Details" then JSON file is getting created in GitHub repository which has the package description. 
If we deploy to Test environment then Package description is not getting updated in Tenant from this JSON file.
![GitHub-Package Deployment](https://github.com/engswee/flashpipe/assets/135332138/7585613f-5bfd-4c6c-809f-524bfc00a3fa)
Please check.

**Comment by xprbj2212** [comment]
@engswee - Will check and update on the second point.

**Comment by xprbj2212** [comment]
@engswee - Tested with update package command and package description are getting updated in Test, Prd Tenants. Thanks.

**Comment by engswee** [comment]
Good to hear that the package descriptions are being updated now. I have also released a new version v3.3.0 that handles description on the designtime artifacts. You should see now that `metainfo.prop` files will be synced between tenant and Git in both directions.
