### ISSUE TITLE
Artifacts is not updating from Github repository

### ISSUE THREAD

**Issue by BoopathiRamasamy** [engswee/flashpipe#31]
Hi @engswee,

Today while syncing up the artifacts from Development to test tenant through GitHub repository we observed the below issues.

Kindly check and suggest us.

1.	IFlow version is not syncing from dev to test tenant:
We have made the changes in iflow in development tenant and IFlow version in the development tenant is 1.0.12, Github MANIFEST.MF also shows the version 1.0.12, but when we move the iflow changes to test tenant, it updated as 1.0.11 from 1.0.10 instead of newer version 1.0.12. Please clarify on this issue.

2.	Externalized parameter in Configuration file is not updated:
We made the changes in externalized parameter in development tenant configure file. Updated the same Github repository tst.prop to update in test tenant. But when we run the workflow to update the changes from GitHub repository to test tenant, the configured values are not getting updated in test tenant. 

3.	IFlow deployment is not skipping when no changes in IFlow version and Configuration file:
We observed that while moving the entire package (due to changes in another iflow in same package) from development to test tenant through Github repository, the iflow which we did not make any change is not skipping and considered the iflow has some design changes and deploying into test tenant again.

[Artifacts is not updating from Github repository.docx](https://github.com/engswee/flashpipe/files/15474707/Artifacts.is.not.updating.from.Github.repository.docx)

Kindly find attached file with screenshot and suggest us.

Thanks
Boopathi

**Comment by engswee** [comment]
Hi @BoopathiRamasamy ,

1. It's hard to tell what is happening without further details. From the screenshot, I'm wondering if you are executing Sync from Dev to Git, and Sync from Git to Test in the same job. If yes, then you need to run these in separate pipelines.

2. Unfortunately, timer configuration is not supported yet.

3. SAP recently changed the length of the MANIEFEST.MF files, so this gets picked up as changes even though there are nothing else changed in the artifact.

**Comment by BoopathiRamasamy** [comment]
Hi @engswee ,

Thanks for the clarification.

For point #1, Yes, we are executing from Dev to Github repository and then from Github repository to test tenant. 
When we move/sync the code from DEV to test tenant through Github repository, the same IFlow version is dev tenant should sync in test tenant. Our case the iflow version in test tenant is 1.0.10 and iflow version in dev tenant is 1.0.12, so when we sync from Dev to test tenant, the same 1.0.12 version should be updated in test tenant. Instead, it updated in test tenant as 1.0.11 from 1.0.10.
The updated version in dev tenant is in MANIFEST.MF file. Is it possible to read this version and update in test tenant version iflow.
There are chances where developer could increase the version (n + n) in development tenant till completion of development and testing and will do the sync once to test tenant once all the development tasks are completed.
 

2. We observed one more issue today, the externalized parameter value is getting truncated. Is there any length restrictions in externalized parameter/configure value in property file?
The older version of iflow in test tenant has the externalize parameter configuration as
Error Occured in DIS to SAP Occupational Illness Info integration : ${property.SAP_MessageProcessingLogID}
The property file has the same value and no changes.
 
When we sync the iflow from dev to test tenant through Github pipeline, this externalized parameter value got truncated to
Error Occured in DIS to SAP Occupational Illness Info integration : 

Please find attached screenshots for the reference and suggest us.

[Externalized parameter values truncated.docx](https://github.com/engswee/flashpipe/files/15483459/Externalized.parameter.values.truncated.docx)

Thanks
Boopathi

**Comment by engswee** [comment]
1. Can you please share your pipeline definition?
2. I think the dynamic property is not handled. I've never come across this use case, so I'm not sure how it behaves. I'd suggest that you only externalise the static part of the value - you can combine externalised values and static values in the same field.

**Comment by BoopathiRamasamy** [comment]
Hi @engswee ,

Thanks for the clarification.
Please find attached pipeline definition and suggest us.
[pipeline.txt](https://github.com/engswee/flashpipe/files/15496829/pipeline.txt)

Thanks
Boopathi

**Comment by engswee** [comment]
Hi @BoopathiRamasamy 

You cannot use the `update artifact` command in the same pipeline after the `sync` command. Please separate them into two separate workflow, and then run the sync pipeline successfully first, check that the GitHub repo is updated correctly before executing the update pipeline.

**Comment by BoopathiRamasamy** [comment]
Hi @engswee,

Thanks for the clarification. We are working on the above suggested changes. We will update you once the changes are completed.

Thanks
Boopathi

**Comment by engswee** [comment]
I'd consider this issue as resolved, so closing it
