### ISSUE TITLE
Deploying to same iflow to same tenant but to different package like QA

### ISSUE THREAD

**Issue by itstushar22** [engswee/flashpipe#36]
I have build jobs to deploy to same tenant but in different package. 
- I copy the same iflow "TestCICD" artifacts and move to new package. And rename with same "TestCICD_Q" and add the new properties folder.
Here is the repo structure.
![image](https://github.com/user-attachments/assets/f806fd2e-75af-44b7-a288-d72e656aa1eb)

- New iflow creation works with designtime creation but deploy to runtime is not working.  see the screenshot below
-
![image](https://github.com/user-attachments/assets/710db31e-a433-4228-bc6d-ad180dea4aa5)

- Also if i try to redeploy using the same job the update fails at designtime since this iflow already exist ,see the screenshot below
![image](https://github.com/user-attachments/assets/d46dc254-6e4c-4e7a-bf27-a6668cc60f85)

**Comment by engswee** [comment]
Hi @itstushar22 

1. For the deployment, the error shows that `artifact-ids` is not set. Please check your configuration
2. For updating the same IFlow to a different package and IFlow ID, I can't tell what is causing the problem from the screenshot. If you could share the configuration of the job, that may help. Alternatively, I suggest you check out [https://github.com/engswee/flashpipe-demo/tree/azure-pipelines](https://github.com/engswee/flashpipe-demo/tree/azure-pipelines) that shows how an artefact can be deployed multiple times to the same tenant but with different package/ID. Note the example is for Azure Pipelines, but the approach should be similar for GitHub Actions.

**Comment by itstushar22** [comment]
thanks for the inputs!
